name: Check versions and urls
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be tagged in release'
        required: true

jobs:
  check:
    name: Check Urls and Versions
    runs-on: windows-latest
    env:
      SCOOP: 'C:\Scoop\user'
    steps:
      - uses: actions/checkout@v2

      - name: Install Scoop
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          echo "$env:SCOOP\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check Versions
        run: |
          .\bin\checkver.ps1
      - name: Check Urls
        run: |
          # Running once for the logs, once for error handling
          .\bin\checkurls.ps1
          .\bin\checkurls.ps1 6> results.txt
          $error_string = Select-String -Path results.txt -Pattern "error"
          if ($error_string -ne $null) {
              Exit 1
          }