name: Update Manifest
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be tagged in release'
        required: true

jobs:
  update-and-verify:
    name: Check Urls and Versions
    runs-on: windows-latest
    env:
      SCOOP: 'C:\Scoop\user'
    steps:
      - uses: actions/checkout@v2

      - name: Install Scoop
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          echo "$env:SCOOP\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Update Manifest
        run: |
          .\bin\updatever.ps1
      - name: Verify Urls
        run: |
          # Running once for logging, once for error handling
          .\bin\checkurls.ps1
          .\bin\checkurls.ps1 6> results.txt
          $error_string = Select-String -Path results.txt -Pattern "error"
          if ($error_string -ne $null) {
              echo "URLS are misconfigured!"
              #Exit 1
          }
      - name: Commit Changes
        run: |
          .\.github\scripts\commit-release.ps1 -version ${{github.event.inputs.version}}

  release:
    runs-on: ubuntu-latest
    needs: [update-and-verify]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{github.event.inputs.version}}
          token: ${{ secrets.GITHUB_TOKEN }}